### ISSUE TITLE
outdated pattern

### ISSUE THREAD

**Issue by execnone** [cazzwastaken/kakhack#6]
![image](https://user-images.githubusercontent.com/107500228/176631650-2deb6605-6669-4a60-aff7-6616a0eef52d.png)

**Comment by execnone** [comment]
how can i fix this?

**Comment by QmM7iXC0D1KsKzW** [comment]
you just change the outdated pattern to the update one, if your lazy just go on Unknowncheats and look at the reverse engineering section for csgo. 
https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-counterstrike-global-offensive-reversal-structs-offsets.html
